Repository joshuadanpeterson/enhanced-dash-mcp, pull requests merged in 2025-06, with the labels that each got.

#2 Add release workflow and changelog links
  .github/workflows/release.yml
  CHANGELOG.md
  docs/changelog_and_ci.md
  tests/test_changelog_links.py
Labels: enhancement, codex

#3 Fix changelog link regex
  docs/changelog_and_ci.md
  tests/test_changelog_links.py
Labels: enhancement, codex

#5 Fix server run with StdioClient
  README.md
  claude-mcp-config.json
  docs/server_usage.md
  enhanced_dash_server.py
  tests/test_main_usage.py
  tests/test_version.py
  warp-mcp-config.json
Labels: bug, enhancement, codex

#7 Fix changelog formatting
  .flake8
  CHANGELOG.md
  README.md
  docs/help.md
  docs/server_usage.md
  enhanced_dash_server.py
  mypy.ini
  tests/test_help_doc.py
  tests/test_project_context_types.py
  tests/test_version.py
Labels: bug, enhancement, codex

#8 Handle Ctrl+C gracefully
  AGENTS.md
  CHANGELOG.md
  README.md
  docs/help.md
  docs/server_usage.md
  enhanced_dash_server.py
  tests/conftest.py
  tests/test_cancel_task.py
  tests/test_keyboard_interrupt.py
  tests/test_version.py
Labels: bug, enhancement, codex

#9 Add rotating logging with tests
  CHANGELOG.md
  README.md
  docs/help.md
  docs/server_usage.md
  enhanced_dash_server.py
  tests/test_logging.py
  tests/test_version.py
Labels: documentation, enhancement, codex

#10 Add startup logging
  CHANGELOG.md
  README.md
  docs/help.md
  docs/server_usage.md
  enhanced_dash_server.py
  tests/test_logging.py
  tests/test_version.py
Labels: bug, documentation, enhancement, codex

#12 Fix limit casting bug and update docs
  CHANGELOG.md
  docs/help.md
  enhanced_dash_server.py
  tests/test_help_doc.py
  tests/test_search_limit.py
  tests/test_version.py
Labels: codex

#13 Add logging for docset directory
  CHANGELOG.md
  README.md
  docs/help.md
  docs/server_usage.md
  enhanced_dash_server.py
  tests/test_docsets_env.py
  tests/test_symlink_docsets.py
  tests/test_version.py
Labels: bug, documentation, enhancement, codex

#15 Fix CHANGELOG headings
  CHANGELOG.md
  docs/help.md
Labels: documentation, codex

#16 docs: 📚 clarify symlink placement
  CHANGELOG.md
  README.md
  docs/help.md
  docs/server_usage.md
  enhanced_dash_server.py
  tests/test_symlink_docsets.py
  tests/test_version.py
Labels: bug, documentation, codex

#17 feat: Allow nested docset directories
  enhanced_dash_server.py
Labels: bug

#18 Fix changelog workflow to preserve history
  .github/workflows/update-changelog.yml
  CHANGELOG.md
  README.md
  docs/help.md
  docs/server_usage.md
  enhanced_dash_server.py
  tests/test_changelog_history.py
  tests/test_nested_docsets.py
  tests/test_version.py
Labels: bug, documentation, enhancement, codex

#19 Fix changelog ordering
  CHANGELOG.md
  README.md
  docs/help.md
  tests/test_changelog_history.py
  tests/test_changelog_order.py
Labels: documentation, enhancement, codex

#21 Organize scripts and configs
  .prompts/README.md
  .prompts/context_priming.md
  AGENTS.md
  AI_Docs/AGENTS.md
  AI_Docs/README.md
  CHANGELOG.md
  README.md
  Specs/README.md
  configs/claude-mcp-config.json
  configs/warp-mcp-config.json
  docs/help.md
  docs/warp-dash-mcp-workflow.md
  scripts/setup-dash-mcp.sh
  scripts/setup-warp-dash-mcp.sh
  scripts/warp-zshrc-additions.sh
  tests/test_help_doc.py
  tests/test_readme_paths.py
Labels: documentation, enhancement, codex

#23 Restore changelog history
  .github/workflows/update-changelog.yml
  CHANGELOG.md
  docs/help.md
  enhanced_dash_server.py
  tests/test_changelog_history.py
  tests/test_version.py
Labels: bug, documentation, codex

#24 fix(setup): 🧹 remove cross-platform references
  CHANGELOG.md
  README.md
  configs/claude-mcp-config.json
  configs/warp-mcp-config.json
  docs/help.md
  docs/warp-dash-mcp-workflow.md
  scripts/setup-dash-mcp.sh
  scripts/setup-warp-dash-mcp.sh
  tests/test_claude_config.py
  tests/test_help_doc.py
  tests/test_setup_scripts.py
Labels: documentation, enhancement, codex
